client_info:
  base_url: python
  module:
    package_path: "/mnt/pypi"
    simple_index_name: "index.html"
    pipeline_save: "pipeline"
  webhooks:
    # url: 0.0.0.0:8000/python/pypi
    url_suffix: "pypi"
    host: "0.0.0.0"
    port: 8000

  repo:
    # url: 0.0.0.0:8001/simple
    host: "0.0.0.0"
    port: 8001

  config:
    url_suffix: "config"
    host: "0.0.0.0"
    port: 8002

  gitlab:
    url: "http://10.2.12.84:8000"
    # BSyK4ZVZzDK47_MeeFYs
    sk: "QlN5SzRaVlp6REs0N19NZWVGWXM="
    timeout: 60
    parse_filename: "requirements.txt"

  ignore_black_key_words:
    mppm: "ERROR"

performance:
  max_workers: 5